---
base_dir: !ENV '${HOME}/datachecks'
datacheck_output_dir: !ENV '${HOME}/datachecks'
datacheck_common_dir: !ENV '${HOME}/datachecks'
hive_uri: 'mysql://test:test@test:3366/ensprod_datachecks_production'
ens_version: 110
eg_version: 57
copy_uri_dropdown: 'https://services.test.ensembl-production.ebi.ac.uk'
datacheck_type: production
get_server_names: 1