---
base_dir: '/app/'
datacheck_output_dir: '/nfs/nobackup/ensembl/ensprod/datachecks'
datacheck_common_dir: '/nfs/panda/ensembl/production/datachecks'
hive_uri: 'mysql://'
server_names_file: '/app/server_names.json'
swagger_file: '/app/swagger.yml'