FROM python:2.7
WORKDIR /app
COPY requirements.txt gunicorn.conf lock_app.py lock_config.py /app/
RUN useradd appuser -u 1000 -g 0 && \
    chown -R 1000:0 /app && \
    cd /app && pip install -r requirements.txt && \
    mkdir instance && \
    touch instance/hc_config.py
USER 1000:0
EXPOSE 4004
ENTRYPOINT ["/usr/local/bin/gunicorn", "--config", "/app/gunicorn.conf", "-b", ":4004", "lock_app:app"]