FROM python:2.7
COPY requirements.txt gunicorn.conf db_app.py db_config.py /
COPY db_config.py.instance_example /instance/db_config.py
COPY celery_app_config.py.example /celery_app_config.py
RUN pip install -r requirements.txt
EXPOSE 8000
ENTRYPOINT ["/usr/local/bin/gunicorn", "--config", "/gunicorn.conf", "-b", ":8000", "db_app:app"]