FROM python:2.7
WORKDIR /app
COPY celery_requirements.txt /app/requirements.txt
COPY email_celery_app_config.py.example /app/email_celery_app_config.py
RUN useradd appuser -u 1000 -g 0 && \
    mkdir -p /app && \
    cd /app && pip install -r requirements.txt && \
    chown 1000:0 /app
USER 1000:0
ENV USER ensembl-production
ENTRYPOINT celery -A ensembl_prodinf.email_tasks -Q email worker --concurrency=20 --loglevel=info