FROM python:2.7
WORKDIR /app
COPY celery_requirements.txt /app/requirements.txt
COPY email_celery_app_config.py.example /app/email_celery_app_config.py
RUN  groupadd appusers && \
    useradd appuser -G appusers && \
    mkdir -p /app && \
    chown appuser:appusers /app && \
    cd /app && pip install -r requirements.txt
USER appuser:appusers
ENV USER ensembl-production
ENTRYPOINT celery -A ensembl_prodinf.email_tasks -Q email worker --concurrency=20 --loglevel=info